--insert into libraryy values(nextval('libraryy_id_seq'), 'The Tartar Steppe','a');
--insert into libraryy values(444, 'Poem Strip','b');
--insert into libraryy values(nextval('libraryy_id_seq'), 'Restless Nights: Selected Stories of Dino Buzzati','c');
--insert into libraryy2 values(nextval('hibernate_sequence'), 'Restless Nights: Selected Stories of Dino Buzzati','c');
